### ISSUE TITLE
关于IPSec的IP分配问题

### ISSUE THREAD

**Issue by lsylsy2** [nevill/racoon-vpn-config#1]
有几个问题希望能够解答一下：
network - 192.168.1.0/24
gateway - 192.168.1.1
wan IP - 1.1.1.1
internal IP - 10.9.9.1

这三个分别指的是什么？
比如 user--openwrt--(internet)--server这样的配置，openwrt和server之间连接
user的IP是多少？tracert外网时候会走什么样的一个路径？
同时，server上假设还运行着openvpn的客户端服务端，那么哪些IP资源需要被保留？

**Comment by nevill** [comment]
@lsylsy2 这是一个 site2site VPN 配置，User IP 属于网段 192.168.1.0/24，假设 User IP 是 192.168.1.2，那么访问的路径是 192.168.1.2 -> 192.168.1.1 -> 10.9.9.1，因此，我这个配置里面会有一个 iptables 的 SNAT 规则来做这个事情

[参考资料](https://github.com/nevill/racoon-vpn-config#reference) 里的几篇读过以后你就能了解大概了吧

抱歉，OpenVPN 我不是很了解，没办法回答你的问题 :sweat:
